CREATE PROCEDURE [dbo].[Users_HasPasswords]
AS
IF (SELECT COUNT(*) FROM Users WHERE [password]='' OR [password] IS NULL) = 0 BEGIN
	IF (SELECT COUNT(*) FROM Users) > 0 BEGIN
		SELECT 1
	END ELSE BEGIN SELECT 0 END
END ELSE BEGIN SELECT 0 END